/* Generated by SharpKit 5 v5.4.4 */

if (typeof(JsTypes) == "undefined")
    var JsTypes = [];
var SMZLib$Types$Vector3 = {
    fullname: "SMZLib.Types.Vector3",
    baseTypeName: "System.Object",
    assemblyName: "SMZLib",
    Kind: "Class",
    definition: {
        ctor: function (x, y, z){
            this._X = 0;
            this._Y = 0;
            this._Z = 0;
            System.Object.ctor.call(this);
            this.set_X(x);
            this.set_Y(y);
            this.set_Z(z);
        },
        X$$: "System.Int32",
        get_X: function (){
            return this._X;
        },
        set_X: function (value){
            this._X = value;
        },
        Y$$: "System.Int32",
        get_Y: function (){
            return this._Y;
        },
        set_Y: function (value){
            this._Y = value;
        },
        Z$$: "System.Int32",
        get_Z: function (){
            return this._Z;
        },
        set_Z: function (value){
            this._Z = value;
        }
    }
};
JsTypes.push(SMZLib$Types$Vector3);

